# Generated by Django 3.1.5 on 2021-01-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('tv', 'TV Show'), ('movie', 'Movie')], max_length=10)),
                ('date_added', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=384)),
                ('duration', models.CharField(max_length=32)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='app.Category')),
                ('countries', models.ManyToManyField(to='app.Country')),
            ],
        ),
    ]
